/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Panel;
import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author Admin
 */
public class RCB extends javax.swing.JFrame {

    /**
     * Creates new form RCB
     */
    public RCB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slRed = new javax.swing.JSlider();
        slGre = new javax.swing.JSlider();
        slBlue = new javax.swing.JSlider();
        lblRed = new javax.swing.JLabel();
        lblGre = new javax.swing.JLabel();
        lblBlue = new javax.swing.JLabel();
        pnColor = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        slRed.setValue(0);
        slRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slRedStateChanged(evt);
            }
        });

        slGre.setValue(0);
        slGre.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slGreStateChanged(evt);
            }
        });

        slBlue.setValue(0);
        slBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slBlueStateChanged(evt);
            }
        });

        lblRed.setForeground(new java.awt.Color(255, 0, 0));
        lblRed.setText("R =");

        lblGre.setForeground(new java.awt.Color(0, 204, 0));
        lblGre.setText("G =");

        lblBlue.setForeground(new java.awt.Color(0, 0, 255));
        lblBlue.setText("B =");

        javax.swing.GroupLayout pnColorLayout = new javax.swing.GroupLayout(pnColor);
        pnColor.setLayout(pnColorLayout);
        pnColorLayout.setHorizontalGroup(
            pnColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );
        pnColorLayout.setVerticalGroup(
            pnColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBlue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slGre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lblRed)))
                .addGap(64, 64, 64)
                .addComponent(pnColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(slRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRed))
                                .addGap(18, 18, 18)
                                .addComponent(slGre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblGre))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(slBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBlue))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slRedStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_slRedStateChanged

    private void slGreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slGreStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_slGreStateChanged

    private void slBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slBlueStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_slBlueStateChanged

    public JLabel getLblBlue() {
        return lblBlue;
    }

    public void setLblBlue(JLabel lblBlue) {
        this.lblBlue = lblBlue;
    }

    public JLabel getLblGre() {
        return lblGre;
    }

    public void setLblGre(JLabel lblGre) {
        this.lblGre = lblGre;
    }

    public JLabel getLblRed() {
        return lblRed;
    }

    public void setLblRed(JLabel lblRed) {
        this.lblRed = lblRed;
    }

    public Panel getPnColor() {
        return pnColor;
    }

    public void setPnColor(Panel pnColor) {
        this.pnColor = pnColor;
    }

    public JSlider getSlBlue() {
        return slBlue;
    }

    public void setSlBlue(JSlider slBlue) {
        this.slBlue = slBlue;
    }

    public JSlider getSlGre() {
        return slGre;
    }

    public void setSlGre(JSlider slGre) {
        this.slGre = slGre;
    }

    public JSlider getSlRed() {
        return slRed;
    }

    public void setSlRed(JSlider slRed) {
        this.slRed = slRed;
    }

    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RCB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RCB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RCB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RCB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RCB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblGre;
    private javax.swing.JLabel lblRed;
    private java.awt.Panel pnColor;
    private javax.swing.JSlider slBlue;
    private javax.swing.JSlider slGre;
    private javax.swing.JSlider slRed;
    // End of variables declaration//GEN-END:variables
}
