/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class Note extends javax.swing.JFrame {

    /**
     * Creates new form Note
     */
    public Note() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findDialog = new javax.swing.JDialog();
        lblnFind = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnCancelFind = new javax.swing.JButton();
        replaceDialog = new javax.swing.JDialog();
        lblRefind = new javax.swing.JLabel();
        lblReplace = new javax.swing.JLabel();
        txtReFind = new javax.swing.JTextField();
        txtRePlace = new javax.swing.JTextField();
        btnFindNext = new javax.swing.JButton();
        btnReplace = new javax.swing.JButton();
        btnRePlaceAl = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        changeFontDialog = new javax.swing.JDialog();
        pnName = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollName = new javax.swing.JScrollPane();
        listFontName = new javax.swing.JList<>();
        PnSytle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFontStyle = new javax.swing.JList<>();
        pnSize = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        scrollFontSize = new javax.swing.JScrollPane();
        listFontSize = new javax.swing.JList<>();
        PnFont = new javax.swing.JPanel();
        txtFontText = new javax.swing.JTextField();
        btnApply = new javax.swing.JButton();
        btnFontCancel = new javax.swing.JButton();
        sp = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mNew = new javax.swing.JMenuItem();
        mOpen = new javax.swing.JMenuItem();
        mSave = new javax.swing.JMenuItem();
        mSaveAs = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        mUndo = new javax.swing.JMenuItem();
        mRedo = new javax.swing.JMenuItem();
        mCut = new javax.swing.JMenuItem();
        mCoppy = new javax.swing.JMenuItem();
        mPate = new javax.swing.JMenuItem();
        mSelectAll = new javax.swing.JMenuItem();
        mFind = new javax.swing.JMenuItem();
        mRePlace = new javax.swing.JMenuItem();
        mChangeFont = new javax.swing.JMenuItem();

        lblnFind.setText("Find What : ");

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnCancelFind.setText("Cancel");
        btnCancelFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findDialogLayout = new javax.swing.GroupLayout(findDialog.getContentPane());
        findDialog.getContentPane().setLayout(findDialogLayout);
        findDialogLayout.setHorizontalGroup(
            findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblnFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        findDialogLayout.setVerticalGroup(
            findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findDialogLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnFind)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addComponent(btnCancelFind)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        lblRefind.setText("Find What: ");

        lblReplace.setText("Replace With: ");

        btnFindNext.setText("Find Next");
        btnFindNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindNextActionPerformed(evt);
            }
        });

        btnReplace.setText("RePlace");
        btnReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceActionPerformed(evt);
            }
        });

        btnRePlaceAl.setText("RePlace All");
        btnRePlaceAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRePlaceAlActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout replaceDialogLayout = new javax.swing.GroupLayout(replaceDialog.getContentPane());
        replaceDialog.getContentPane().setLayout(replaceDialogLayout);
        replaceDialogLayout.setHorizontalGroup(
            replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(replaceDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(replaceDialogLayout.createSequentialGroup()
                        .addGroup(replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRefind)
                            .addComponent(lblReplace))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReFind, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFindNext, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(btnReplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, replaceDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRePlaceAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        replaceDialogLayout.setVerticalGroup(
            replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(replaceDialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRefind)
                    .addComponent(txtReFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindNext))
                .addGap(25, 25, 25)
                .addGroup(replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(replaceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblReplace)
                        .addComponent(txtRePlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReplace))
                .addGap(24, 24, 24)
                .addComponent(btnRePlaceAl)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel1.setText("Font");

        scrollName.setViewportView(listFontName);

        javax.swing.GroupLayout pnNameLayout = new javax.swing.GroupLayout(pnName);
        pnName.setLayout(pnNameLayout);
        pnNameLayout.setHorizontalGroup(
            pnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNameLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNameLayout.setVerticalGroup(
            pnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNameLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollName, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Font Style");

        listFontStyle.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Regular", "Bold", "Italic", "Bold Italic" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listFontStyle);

        javax.swing.GroupLayout PnSytleLayout = new javax.swing.GroupLayout(PnSytle);
        PnSytle.setLayout(PnSytleLayout);
        PnSytleLayout.setHorizontalGroup(
            PnSytleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnSytleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnSytleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addGroup(PnSytleLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnSytleLayout.setVerticalGroup(
            PnSytleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnSytleLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel3.setText("Size");

        listFontSize.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollFontSize.setViewportView(listFontSize);

        javax.swing.GroupLayout pnSizeLayout = new javax.swing.GroupLayout(pnSize);
        pnSize.setLayout(pnSizeLayout);
        pnSizeLayout.setHorizontalGroup(
            pnSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSizeLayout.createSequentialGroup()
                .addGroup(pnSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(scrollFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        pnSizeLayout.setVerticalGroup(
            pnSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSizeLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollFontSize)
                .addContainerGap())
        );

        txtFontText.setText("This is a text");

        javax.swing.GroupLayout PnFontLayout = new javax.swing.GroupLayout(PnFont);
        PnFont.setLayout(PnFontLayout);
        PnFontLayout.setHorizontalGroup(
            PnFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnFontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFontText)
                .addContainerGap())
        );
        PnFontLayout.setVerticalGroup(
            PnFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnFontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFontText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnFontCancel.setText("Cancel");
        btnFontCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFontCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeFontDialogLayout = new javax.swing.GroupLayout(changeFontDialog.getContentPane());
        changeFontDialog.getContentPane().setLayout(changeFontDialogLayout);
        changeFontDialogLayout.setHorizontalGroup(
            changeFontDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeFontDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeFontDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PnFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(changeFontDialogLayout.createSequentialGroup()
                        .addComponent(pnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PnSytle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(changeFontDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeFontDialogLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(changeFontDialogLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(changeFontDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFontCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        changeFontDialogLayout.setVerticalGroup(
            changeFontDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeFontDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeFontDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnSytle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(changeFontDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeFontDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PnFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changeFontDialogLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnApply)
                        .addGap(18, 18, 18)
                        .addComponent(btnFontCancel)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        txtContent.setColumns(20);
        txtContent.setRows(5);
        sp.setViewportView(txtContent);

        menuFile.setText("File");

        mNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mNew.setText("New");
        mNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNewActionPerformed(evt);
            }
        });
        menuFile.add(mNew);

        mOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mOpen.setText("Open");
        mOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOpenActionPerformed(evt);
            }
        });
        menuFile.add(mOpen);

        mSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mSave.setText("Save");
        mSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveActionPerformed(evt);
            }
        });
        menuFile.add(mSave);

        mSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mSaveAs.setText("Save As");
        mSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveAsActionPerformed(evt);
            }
        });
        menuFile.add(mSaveAs);

        mExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_MASK));
        mExit.setText("Exit");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        menuFile.add(mExit);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");

        mUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        mUndo.setText("Undo");
        mUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUndoActionPerformed(evt);
            }
        });
        menuEdit.add(mUndo);

        mRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        mRedo.setText("Redo");
        mRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRedoActionPerformed(evt);
            }
        });
        menuEdit.add(mRedo);

        mCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mCut.setText("Cut");
        mCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCutActionPerformed(evt);
            }
        });
        menuEdit.add(mCut);

        mCoppy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mCoppy.setText("Coppy");
        mCoppy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCoppyActionPerformed(evt);
            }
        });
        menuEdit.add(mCoppy);

        mPate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mPate.setText("Pate");
        mPate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPateActionPerformed(evt);
            }
        });
        menuEdit.add(mPate);

        mSelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mSelectAll.setText("Select All");
        mSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSelectAllActionPerformed(evt);
            }
        });
        menuEdit.add(mSelectAll);

        mFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mFind.setText("Find");
        mFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFindActionPerformed(evt);
            }
        });
        menuEdit.add(mFind);

        mRePlace.setText("Replace");
        mRePlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRePlaceActionPerformed(evt);
            }
        });
        menuEdit.add(mRePlace);

        mChangeFont.setText("Change Font");
        mChangeFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mChangeFontActionPerformed(evt);
            }
        });
        menuEdit.add(mChangeFont);

        menuBar.add(menuEdit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPnFont() {
        return PnFont;
    }

    public void setPnFont(JPanel PnFont) {
        this.PnFont = PnFont;
    }

    public JPanel getPnSytle() {
        return PnSytle;
    }

    public void setPnSytle(JPanel PnSytle) {
        this.PnSytle = PnSytle;
    }

    public JButton getBtnApply() {
        return btnApply;
    }

    public void setBtnApply(JButton btnApply) {
        this.btnApply = btnApply;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public JButton getBtnCancelFind() {
        return btnCancelFind;
    }

    public void setBtnCancelFind(JButton btnCancelFind) {
        this.btnCancelFind = btnCancelFind;
    }

    public JButton getBtnFind() {
        return btnFind;
    }

    public void setBtnFind(JButton btnFind) {
        this.btnFind = btnFind;
    }

    public JButton getBtnFindNext() {
        return btnFindNext;
    }

    public void setBtnFindNext(JButton btnFindNext) {
        this.btnFindNext = btnFindNext;
    }

    public JButton getBtnFontCancel() {
        return btnFontCancel;
    }

    public void setBtnFontCancel(JButton btnFontCancel) {
        this.btnFontCancel = btnFontCancel;
    }

    public JButton getBtnRePlaceAl() {
        return btnRePlaceAl;
    }

    public void setBtnRePlaceAl(JButton btnRePlaceAl) {
        this.btnRePlaceAl = btnRePlaceAl;
    }

    public JButton getBtnReplace() {
        return btnReplace;
    }

    public void setBtnReplace(JButton btnReplace) {
        this.btnReplace = btnReplace;
    }

    public JDialog getChangeFontDialog() {
        return changeFontDialog;
    }

    public void setChangeFontDialog(JDialog changeFontDialog) {
        this.changeFontDialog = changeFontDialog;
    }

    public JDialog getFindDialog() {
        return findDialog;
    }

    public void setFindDialog(JDialog findDialog) {
        this.findDialog = findDialog;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblRefind() {
        return lblRefind;
    }

    public void setLblRefind(JLabel lblRefind) {
        this.lblRefind = lblRefind;
    }

    public JLabel getLblReplace() {
        return lblReplace;
    }

    public void setLblReplace(JLabel lblReplace) {
        this.lblReplace = lblReplace;
    }

    public JLabel getLblnFind() {
        return lblnFind;
    }

    public void setLblnFind(JLabel lblnFind) {
        this.lblnFind = lblnFind;
    }

    public JList<String> getListFontName() {
        return listFontName;
    }

    public void setListFontName(JList<String> listFontName) {
        this.listFontName = listFontName;
    }

    public JList<String> getListFontSize() {
        return listFontSize;
    }

    public void setListFontSize(JList<String> listFontSize) {
        this.listFontSize = listFontSize;
    }

    public JList<String> getListFontStyle() {
        return listFontStyle;
    }

    public void setListFontStyle(JList<String> listFontStyle) {
        this.listFontStyle = listFontStyle;
    }

    public JMenuItem getmChangeFont() {
        return mChangeFont;
    }

    public void setmChangeFont(JMenuItem mChangeFont) {
        this.mChangeFont = mChangeFont;
    }

    public JMenuItem getmCoppy() {
        return mCoppy;
    }

    public void setmCoppy(JMenuItem mCoppy) {
        this.mCoppy = mCoppy;
    }

    public JMenuItem getmCut() {
        return mCut;
    }

    public void setmCut(JMenuItem mCut) {
        this.mCut = mCut;
    }

    public JMenuItem getmExit() {
        return mExit;
    }

    public void setmExit(JMenuItem mExit) {
        this.mExit = mExit;
    }

    public JMenuItem getmFind() {
        return mFind;
    }

    public void setmFind(JMenuItem mFind) {
        this.mFind = mFind;
    }

    public JMenuItem getmNew() {
        return mNew;
    }

    public void setmNew(JMenuItem mNew) {
        this.mNew = mNew;
    }

    public JMenuItem getmOpen() {
        return mOpen;
    }

    public void setmOpen(JMenuItem mOpen) {
        this.mOpen = mOpen;
    }

    public JMenuItem getmPate() {
        return mPate;
    }

    public void setmPate(JMenuItem mPate) {
        this.mPate = mPate;
    }

    public JMenuItem getmRePlace() {
        return mRePlace;
    }

    public void setmRePlace(JMenuItem mRePlace) {
        this.mRePlace = mRePlace;
    }

    public JMenuItem getmRedo() {
        return mRedo;
    }

    public void setmRedo(JMenuItem mRedo) {
        this.mRedo = mRedo;
    }

    public JMenuItem getmSave() {
        return mSave;
    }

    public void setmSave(JMenuItem mSave) {
        this.mSave = mSave;
    }

    public JMenuItem getmSaveAs() {
        return mSaveAs;
    }

    public void setmSaveAs(JMenuItem mSaveAll) {
        this.mSaveAs = mSaveAll;
    }

    public JMenuItem getmSelectAll() {
        return mSelectAll;
    }

    public void setmSelectAll(JMenuItem mSelectAll) {
        this.mSelectAll = mSelectAll;
    }

    public JMenuItem getmUndo() {
        return mUndo;
    }

    public void setmUndo(JMenuItem mUndo) {
        this.mUndo = mUndo;
    }

    

    public JMenu getMenuEdit() {
        return menuEdit;
    }

    public void setMenuEdit(JMenu menuEdit) {
        this.menuEdit = menuEdit;
    }

    public JMenu getMenuFile() {
        return menuFile;
    }

    public void setMenuFile(JMenu menuFile) {
        this.menuFile = menuFile;
    }

    public JPanel getPnName() {
        return pnName;
    }

    public void setPnName(JPanel pnName) {
        this.pnName = pnName;
    }

    public JPanel getPnSize() {
        return pnSize;
    }

    public void setPnSize(JPanel pnSize) {
        this.pnSize = pnSize;
    }

    public JDialog getReplaceDialog() {
        return replaceDialog;
    }

    public void setReplaceDialog(JDialog replaceDialog) {
        this.replaceDialog = replaceDialog;
    }

    public JScrollPane getScrollFontSize() {
        return scrollFontSize;
    }

    public void setScrollFontSize(JScrollPane scrollFontSize) {
        this.scrollFontSize = scrollFontSize;
    }

    public JScrollPane getScrollName() {
        return scrollName;
    }

    public void setScrollName(JScrollPane scrollName) {
        this.scrollName = scrollName;
    }

    public JScrollPane getSp() {
        return sp;
    }

    public void setSp(JScrollPane sp) {
        this.sp = sp;
    }

    public JTextArea getTxtContent() {
        return txtContent;
    }

    public void setTxtContent(JTextArea txtContent) {
        this.txtContent = txtContent;
    }

    public JTextField getTxtFind() {
        return txtFind;
    }

    public void setTxtFind(JTextField txtFind) {
        this.txtFind = txtFind;
    }

    public JTextField getTxtFontText() {
        return txtFontText;
    }

    public void setTxtFontText(JTextField txtFont) {
        this.txtFontText = txtFont;
    }

    public JTextField getTxtReFind() {
        return txtReFind;
    }

    public void setTxtReFind(JTextField txtReFind) {
        this.txtReFind = txtReFind;
    }

    public JTextField getTxtRePlace() {
        return txtRePlace;
    }

    public void setTxtRePlace(JTextField txtRePlace) {
        this.txtRePlace = txtRePlace;
    }
   

    private void mSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mSaveAsActionPerformed

    private void mRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRedoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mRedoActionPerformed

    private void mCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCutActionPerformed

    private void mNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mNewActionPerformed

    private void mOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mOpenActionPerformed

    private void mSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mSaveActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mExitActionPerformed

    private void mUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mUndoActionPerformed

    private void mCoppyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCoppyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCoppyActionPerformed

    private void mPateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPateActionPerformed

    private void mSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSelectAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mSelectAllActionPerformed

    private void mFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mFindActionPerformed

    private void mRePlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRePlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mRePlaceActionPerformed

    private void mChangeFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mChangeFontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mChangeFontActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnCancelFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFindActionPerformed

    private void btnFindNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindNextActionPerformed

    private void btnReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReplaceActionPerformed

    private void btnRePlaceAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRePlaceAlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRePlaceAlActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnFontCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFontCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFontCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Note().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnFont;
    private javax.swing.JPanel PnSytle;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelFind;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFindNext;
    private javax.swing.JButton btnFontCancel;
    private javax.swing.JButton btnRePlaceAl;
    private javax.swing.JButton btnReplace;
    private javax.swing.JDialog changeFontDialog;
    private javax.swing.JDialog findDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRefind;
    private javax.swing.JLabel lblReplace;
    private javax.swing.JLabel lblnFind;
    private javax.swing.JList<String> listFontName;
    private javax.swing.JList<String> listFontSize;
    private javax.swing.JList<String> listFontStyle;
    private javax.swing.JMenuItem mChangeFont;
    private javax.swing.JMenuItem mCoppy;
    private javax.swing.JMenuItem mCut;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenuItem mFind;
    private javax.swing.JMenuItem mNew;
    private javax.swing.JMenuItem mOpen;
    private javax.swing.JMenuItem mPate;
    private javax.swing.JMenuItem mRePlace;
    private javax.swing.JMenuItem mRedo;
    private javax.swing.JMenuItem mSave;
    private javax.swing.JMenuItem mSaveAs;
    private javax.swing.JMenuItem mSelectAll;
    private javax.swing.JMenuItem mUndo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JPanel pnName;
    private javax.swing.JPanel pnSize;
    private javax.swing.JDialog replaceDialog;
    private javax.swing.JScrollPane scrollFontSize;
    private javax.swing.JScrollPane scrollName;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtFontText;
    private javax.swing.JTextField txtReFind;
    private javax.swing.JTextField txtRePlace;
    // End of variables declaration//GEN-END:variables
}
