/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Point;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class SimplePaint extends javax.swing.JFrame {

    /**
     * Creates new form SimplePaint
     */
    public SimplePaint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JPanel();
        btnblack = new javax.swing.JButton();
        btnred = new javax.swing.JButton();
        btngre = new javax.swing.JButton();
        btnblue = new javax.swing.JButton();
        btnleon = new javax.swing.JButton();
        btnvio = new javax.swing.JButton();
        btnyelow = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        display.setBackground(new java.awt.Color(255, 255, 255));
        display.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                displayMouseDragged(evt);
            }
        });
        display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                displayMousePressed(evt);
            }
        });

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnblack.setBackground(new java.awt.Color(0, 0, 0));
        btnblack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblackActionPerformed(evt);
            }
        });

        btnred.setBackground(new java.awt.Color(255, 0, 0));
        btnred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnredActionPerformed(evt);
            }
        });

        btngre.setBackground(new java.awt.Color(0, 204, 0));
        btngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngreActionPerformed(evt);
            }
        });

        btnblue.setBackground(new java.awt.Color(0, 0, 204));
        btnblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblueActionPerformed(evt);
            }
        });

        btnleon.setBackground(new java.awt.Color(102, 255, 255));
        btnleon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleonActionPerformed(evt);
            }
        });

        btnvio.setBackground(new java.awt.Color(255, 0, 255));
        btnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvioActionPerformed(evt);
            }
        });

        btnyelow.setBackground(new java.awt.Color(255, 255, 0));
        btnyelow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyelowActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnblack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngre, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnblue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnleon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnyelow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnblack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnred, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnblue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnleon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnyelow, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnblackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnblackActionPerformed

    private void btnredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnredActionPerformed

    private void btngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngreActionPerformed

    private void btnblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnblueActionPerformed

    private void btnleonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnleonActionPerformed

    private void btnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvioActionPerformed

    private void btnyelowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyelowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnyelowActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_displayMouseClicked

    private void displayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayMousePressed

    private void displayMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_displayMouseDragged
               
    public JButton getBtnblack() {
        return btnblack;
    }

    public void setBtnblack(JButton btnblack) {
        this.btnblack = btnblack;
    }

    public JButton getBtnblue() {
        return btnblue;
    }

    public void setBtnblue(JButton btnblue) {
        this.btnblue = btnblue;
    }

    public JButton getBtnclear() {
        return btnclear;
    }

    public void setBtnclear(JButton btnclear) {
        this.btnclear = btnclear;
    }

    public JButton getBtngre() {
        return btngre;
    }

    public void setBtngre(JButton btngre) {
        this.btngre = btngre;
    }

    public JButton getBtnleon() {
        return btnleon;
    }

    public void setBtnleon(JButton btnleon) {
        this.btnleon = btnleon;
    }

    public JButton getBtnred() {
        return btnred;
    }

    public void setBtnred(JButton btnred) {
        this.btnred = btnred;
    }

    public JButton getBtnvio() {
        return btnvio;
    }

    public void setBtnvio(JButton btnvio) {
        this.btnvio = btnvio;
    }

    public JButton getBtnyelow() {
        return btnyelow;
    }

    public void setBtnyelow(JButton btnyelow) {
        this.btnyelow = btnyelow;
    }

    public JPanel getDisplay() {
        return display;
    }

    public void setDisplay(JPanel display) {
        this.display = display;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimplePaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimplePaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimplePaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimplePaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimplePaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnblack;
    private javax.swing.JButton btnblue;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btngre;
    private javax.swing.JButton btnleon;
    private javax.swing.JButton btnred;
    private javax.swing.JButton btnvio;
    private javax.swing.JButton btnyelow;
    private javax.swing.JPanel display;
    // End of variables declaration//GEN-END:variables
}
