/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static java.awt.Color.*;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author Admin
 */
public class ChooseColor extends javax.swing.JFrame {

    /**
     * Creates new form ChooseColor
     */
    public ChooseColor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupRB = new javax.swing.ButtonGroup();
        rbred = new javax.swing.JRadioButton();
        rbblue = new javax.swing.JRadioButton();
        rbgreen = new javax.swing.JRadioButton();
        rbblack = new javax.swing.JRadioButton();
        ColorText = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GroupRB.add(rbred);
        rbred.setText("Red");
        rbred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbredActionPerformed(evt);
            }
        });

        GroupRB.add(rbblue);
        rbblue.setText("Blue");
        rbblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbblueActionPerformed(evt);
            }
        });

        GroupRB.add(rbgreen);
        rbgreen.setText("Green");
        rbgreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbgreenActionPerformed(evt);
            }
        });

        GroupRB.add(rbblack);
        rbblack.setText("Black");
        rbblack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbblackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbred)
                    .addComponent(rbblue)
                    .addComponent(rbgreen)
                    .addComponent(rbblack))
                .addContainerGap(114, Short.MAX_VALUE))
            .addComponent(ColorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(rbred)
                .addGap(18, 18, 18)
                .addComponent(rbblue)
                .addGap(18, 18, 18)
                .addComponent(rbgreen)
                .addGap(18, 18, 18)
                .addComponent(rbblack)
                .addGap(18, 18, 18)
                .addComponent(ColorText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbredActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbredActionPerformed

    private void rbblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbblueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbblueActionPerformed

    private void rbgreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbgreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbgreenActionPerformed

    private void rbblackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbblackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbblackActionPerformed

    public JButton getColorText() {
        return ColorText;
    }

    public void setColorText(JButton Text) {
        this.ColorText = Text;
    }

    

    public JRadioButton getRbblack() {
        return rbblack;
    }

    public void setRbblack(JRadioButton rbblack) {
        this.rbblack = rbblack;
    }

    public JRadioButton getRbblue() {
        return rbblue;
    }

    public void setRbblue(JRadioButton rbblue) {
        this.rbblue = rbblue;
    }

    public JRadioButton getRbgreen() {
        return rbgreen;
    }

    public void setRbgreen(JRadioButton rbgreen) {
        this.rbgreen = rbgreen;
    }

    public JRadioButton getRbred() {
        return rbred;
    }

    public void setRbred(JRadioButton rbred) {
        this.rbred = rbred;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ColorText;
    private javax.swing.ButtonGroup GroupRB;
    private javax.swing.JRadioButton rbblack;
    private javax.swing.JRadioButton rbblue;
    private javax.swing.JRadioButton rbgreen;
    private javax.swing.JRadioButton rbred;
    // End of variables declaration//GEN-END:variables
}
